channels:
- conda-forge
dependencies:
- python=3.12.1
- pip<=25.3
- pip:
  - mlflow==3.7.0
  - numpy==1.26.4
  - pandas==2.1.4
  - psutil==7.0.0
  - pyarrow==14.0.2
  - scikit-learn==1.8.0
  - scipy==1.16.3
  - xgboost==3.1.2
name: mlflow-env
